services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "6005:6000"
    restart: unless-stopped
    container_name: tts-frontend
    environment:
      SERVER_NAME: ${SERVER_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - tts-network

  backend:
    build:
      context: ./backend
    ports:
      - "5005:5000"
    restart: unless-stopped
    container_name: tts-backend
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_PORT: ${BACKEND_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_SENDER_PASSWORD: ${EMAIL_SENDER_PASSWORD}
      EMAIL_SENDER_PORT: ${EMAIL_SENDER_PORT}
      EMAIL_SENDER_HOST: ${EMAIL_SENDER_HOST}
      REDIS_URL: ${REDIS_URL}
      TTS_SERVICE_URL: ${TTS_SERVICE_URL}
    depends_on:
      - redis
      - tts
    networks:
      - tts-network

  tts:
    image: danisojo/spanish-f5:v1
    container_name: f5-tts-spanish
    command: f5-tts_infer-gradio --port 7860 --host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - tts-network

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: tts-redis
    networks:
      - tts-network

networks:
  tts-network:
    driver: bridge